import type { Metadata } from "next";
import { Libre_Bodoni } from "next/font/google";
import "./globals.css";

const geistSans = Libre_Bodoni({
  variable: "--font-libre-bodoni-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Crown Handbook App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
